name: 11
timestamp: 1464336702
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home-climat
  timestamp: 1456588474
positions:
  title: 'Module Position'
  topcontakt: 'Module Position'
  slider: 'Module Position'
  predlagaem: 'Widget Мы предалагем'
  module-position: 'Module Position'
  mojem: 'Module Position'
  prosmet: 'Module Position'
  oshibki: 'Получить консультацию'
  slideset-1: 'Module Position'
  mymaps: 'Module Position'
  footer: 'Module Position'
  polcon: 'Module Position'
  contakt: Контакт
