version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home-climat
  timestamp: 1456588474
layout:
  /header/:
    -
      - 'logo-4680 12'
      - 'position-position-8621 60'
      - 'position-position-1734 28'
  /navigation/: {  }
  /showcase-1/:
    -
      - 'spacer-spacer-9494 40'
      - 'menu-7687 33'
      - 'spacer-spacer-7236 27'
    -
      - position-position-8498
    -
      - position-module-1188
  /showcase-2/:
    -
      - custom-2729
  /showcase-3/:
    -
      - position-position-6440
    -
      - position-position-4227
  /feature/:
    -
      - 'position-position-4371 65'
      - 'position-position-8320 35'
  /subfeature-1/:
    -
      - custom-7886
  /subfeature-2/:
    -
      - position-position-8030
  /pricetitle/:
    -
      - custom-7942
  /price/:
    -
      - position-module-6417
  /posttitle/: {  }
  /modstrah/: {  }
  /subfeature-3/:
    -
      - custom-4955
  /main/:
    -
      - position-position-6759
  /footer/:
    -
      - custom-1437
    -
      - position-position-5496
    -
      - position-position-9427
  /footer-2/:
    -
      - position-position-2319
    -
      - 'spacer-3279 33.3'
      - 'position-position-4134 33.3'
      - 'spacer-1603 33.3'
    -
      - copyright-2857
  /footer-3/: {  }
  /footer-4/: {  }
  offcanvas: {  }
structure:
  header:
    attributes:
      boxed: ''
      class: top-head
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase-1:
    type: section
    attributes:
      boxed: '2'
      class: ''
  showcase-2:
    type: section
    attributes:
      boxed: ''
  showcase-3:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
      class: reclam-1
  subfeature-1:
    type: section
    subtype: feature
    attributes:
      boxed: ''
      class: bgtit
  subfeature-2:
    type: section
    subtype: feature
    attributes:
      boxed: ''
  pricetitle:
    type: section
    attributes:
      boxed: ''
      class: bgtit
  price:
    type: section
    attributes:
      boxed: ''
  posttitle:
    type: section
    attributes:
      boxed: ''
  modstrah:
    type: section
    attributes:
      boxed: ''
  subfeature-3:
    type: section
    subtype: feature
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: '2'
      class: ''
  footer-2:
    attributes:
      boxed: ''
  footer-3:
    attributes:
      boxed: ''
  footer-4:
    attributes:
      boxed: ''
content:
  logo-4680:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://logo.png'
    block:
      id: bl-logo
      variations: nomarginall
  position-position-8621:
    title: 'Module Position'
    attributes:
      key: title
    block:
      variations: nopaddingall
  position-position-1734:
    title: 'Module Position'
    attributes:
      key: topcontakt
    block:
      variations: nopaddingall
  spacer-spacer-9494:
    block:
      class: muthon
  menu-7687:
    attributes:
      menu: twomenu
    block:
      class: muthon
  spacer-spacer-7236:
    block:
      class: muthon
  position-position-8498:
    title: 'Module Position'
    attributes:
      key: slider
    block:
      variations: 'nopaddingall nomarginall'
  position-module-1188:
    title: 'Module Instance'
    attributes:
      module_id: '97'
      key: module-instance
  custom-2729:
    title: 'Мы предлагаем'
    attributes:
      html: '<div class="tithom">МЫ ПРЕДЛАГАЕМ</div>'
    block:
      variations: 'center nomarginall'
  position-position-6440:
    title: 'Widget Мы предалагем'
    attributes:
      key: predlagaem
  position-position-4227:
    title: 'Module Position'
    attributes:
      key: module-position
  position-position-4371:
    title: 'Module Position'
    attributes:
      key: mojem
    block:
      variations: 'nopaddingall nomarginall'
  position-position-8320:
    title: 'Module Position'
    attributes:
      key: prosmet
    block:
      id: prsmet
  custom-7886:
    title: 'Title получить консультацию'
    attributes:
      html: '<div class="tithom">ЛЕГКО ЛИ УСТАНОВИТЬ КОНДИЦИОНЕР?</div>'
    block:
      variations: 'nomarginall center'
  position-position-8030:
    title: 'Получить консультацию'
    attributes:
      key: oshibki
  custom-7942:
    title: 'Прайс лист титул'
    attributes:
      html: '<a id="price"></a><div class="tithom"><a name="price" style="color: #666;">ПРАЙС ЛИСТ</a></div>'
    block:
      id: titprlist
      variations: 'nomarginall center'
  position-module-6417:
    title: 'Module Instance'
    attributes:
      module_id: '103'
      key: module-instance
    block:
      variations: nomarginall
  custom-4955:
    title: 'Title Отзывы'
    attributes:
      html: '<a id="otziv"></a><div class="tithom">ОТЗЫВЫ НАШИХ КЛИЕНТОВ</div>'
    block:
      variations: 'center nomarginall'
  position-position-6759:
    title: 'Module Position'
    attributes:
      key: slideset-1
  custom-1437:
    title: 'Title Наши контакты'
    attributes:
      html: '<a id="kontakt"></a><div class="tithom titpad">НАШИ КОНТАКТЫ</div>'
    block:
      variations: center
  position-position-5496:
    title: 'Module Position'
    attributes:
      key: mymaps
    block:
      class: tpmap
      variations: 'nopaddingall nomarginall'
  position-position-9427:
    title: 'Module Position'
    attributes:
      key: footer
  position-position-2319:
    title: 'Module Position'
    attributes:
      key: polcon
    block:
      variations: 'nopaddingall nomarginall'
  position-position-4134:
    title: Контакт
    attributes:
      key: contakt
    block:
      variations: 'nopaddingall nomarginall center'
  copyright-2857:
    attributes:
      owner: '2008-20016 Установка и обслуживание кондиционеров в Москве'
    block:
      class: copyr
      variations: 'nopaddingall nomarginall center'
