name: 12
timestamp: 1462108207
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home-climat
  timestamp: 1453840631
positions:
  title: 'Module Position'
  topcontakt: 'Top Контакт'
  slider: 'Module Position'
  predlagaem: 'Widget Мы предалагем'
  module-position: 'Module Position'
  mojem: 'Module Position'
  prosmet: 'Module Position'
  oshibki: 'Получить консультацию'
  slideset-1: 'Module Position'
  mymaps: 'Module Position'
  footer: 'Module Position'
  polcon: 'Получить консультацию'
  contakt: Contact
