version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home-climat
  timestamp: 1453840631
layout:
  /header/:
    -
      - 'logo-4680 12'
      - 'position-position-4069 63'
      - 'position-position-6499 25'
  /navigation/: {  }
  /showcase-1/:
    -
      - position-position-6984
    -
      - position-module-8653
  /showcase-2/:
    -
      - custom-6258
  /showcase-3/:
    -
      - position-position-1082
    -
      - position-position-7046
  /feature/:
    -
      - 'position-position-1254 65'
      - 'position-position-4786 35'
  /subfeature-1/:
    -
      - custom-6729
  /subfeature-2/:
    -
      - position-position-7155
  /subfeature-3/:
    -
      - custom-9089
  /main/:
    -
      - position-position-6676
  /footer/:
    -
      - custom-1437
    -
      - position-position-5496
    -
      - position-position-2692
  /footer-2/:
    -
      - position-position-9357
    -
      - 'spacer-6572 33.3'
      - 'position-position-4951 33.3'
      - 'spacer-7478 33.3'
    -
      - copyright-3933
  /footer-3/: {  }
  /footer-4/: {  }
  offcanvas: {  }
structure:
  header:
    attributes:
      boxed: ''
      class: top-head
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase-1:
    type: section
    attributes:
      boxed: '2'
      class: ''
  showcase-2:
    type: section
    attributes:
      boxed: ''
  showcase-3:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
      class: reclam-1
  subfeature-1:
    type: section
    subtype: feature
    attributes:
      boxed: ''
      class: bgtit
  subfeature-2:
    type: section
    subtype: feature
    attributes:
      boxed: ''
  subfeature-3:
    type: section
    subtype: feature
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: '2'
      class: ''
  footer-2:
    attributes:
      boxed: ''
  footer-3:
    attributes:
      boxed: ''
  footer-4:
    attributes:
      boxed: ''
content:
  logo-4680:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://logo.png'
    block:
      id: bl-logo
      variations: nomarginall
  position-position-4069:
    title: 'Module Position'
    attributes:
      key: title
    block:
      variations: nopaddingall
  position-position-6499:
    title: 'Top Контакт'
    attributes:
      key: topcontakt
      chrome: ''
    block:
      variations: nopaddingall
  position-position-6984:
    title: 'Module Position'
    attributes:
      key: slider
    block:
      variations: 'nopaddingall nomarginall'
  position-module-8653:
    title: 'Module Instance'
    attributes:
      module_id: '97'
      key: module-instance
  custom-6258:
    title: 'Мы предагаем'
    attributes:
      html: '<div class="tithom">МЫ ПРЕДЛАГАЕМ</div>'
    block:
      variations: 'center nomarginall'
  position-position-1082:
    title: 'Widget Мы предалагем'
    attributes:
      key: predlagaem
  position-position-7046:
    title: 'Module Position'
    attributes:
      key: module-position
    block:
      variations: center
  position-position-1254:
    title: 'Module Position'
    attributes:
      key: mojem
    block:
      variations: 'nopaddingall nomarginall'
  position-position-4786:
    title: 'Module Position'
    attributes:
      key: prosmet
    block:
      id: prsmet
  custom-6729:
    title: 'Title Консультация'
    attributes:
      html: '<div class="tithom">ЛЕГКО ЛИ УСТАНОВИТЬ КОНДИЦИОНЕР?</div>'
    block:
      variations: 'center nomarginall'
  position-position-7155:
    title: 'Получить консультацию'
    attributes:
      key: oshibki
  custom-9089:
    title: 'Title Отзывы'
    attributes:
      html: '<div class="tithom">ОТЗЫВЫ НАШИХ КЛИЕНТОВ</div>'
    block:
      variations: 'center nomarginall'
  position-position-6676:
    title: 'Module Position'
    attributes:
      key: slideset-1
  custom-1437:
    title: 'Title Наши контакты'
    attributes:
      html: '<div class="tithom titpad">НАШИ КОНТАКТЫ</div>'
    block:
      variations: 'center nomarginall'
  position-position-5496:
    title: 'Module Position'
    attributes:
      key: mymaps
    block:
      class: tpmap
      variations: 'nopaddingall nomarginall'
  position-position-2692:
    title: 'Module Position'
    attributes:
      key: footer
  position-position-9357:
    title: 'Получить консультацию'
    attributes:
      key: polcon
    block:
      variations: 'nopaddingall nomarginall'
  position-position-4951:
    title: Contact
    attributes:
      key: contakt
    block:
      variations: 'nomarginall nopaddingall center'
  copyright-3933:
    attributes:
      owner: '2008-20016 Установка и обслуживание кондиционеров в Москве'
    block:
      class: copyr
      variations: 'nopaddingall nomarginall center'
