version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home-climat
  timestamp: 1453568319
layout:
  /header/:
    -
      - 'logo-5408 20'
      - 'custom-9139 47'
      - 'custom-8352 33'
  /navigation/: {  }
  /showcase/:
    -
      - position-position-2708
  /showcase-2/:
    -
      - custom-2879
  /showcase-3/:
    -
      - custom-7663
  /feature/:
    -
      - custom-5650
  /subfeature-a/: {  }
  /subfeature-b/: {  }
  /subfeature-c/: {  }
  /subfeature-d/: {  }
  /main/:
    -
      - system-messages-6455
    -
      - sample-2
  /footer/:
    -
      - position-footer
    -
      - copyright-8814
  offcanvas:
    -
      - mobile-menu-6240
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  showcase-2:
    type: section
    attributes:
      boxed: ''
  showcase-3:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  subfeature-a:
    type: section
    attributes:
      boxed: ''
  subfeature-b:
    type: section
    attributes:
      boxed: ''
  subfeature-c:
    type: section
    attributes:
      boxed: ''
  subfeature-d:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  logo-5408:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://logo.png'
    block:
      id: bl-logo
  custom-9139:
    title: Title
  custom-8352:
    title: Phone
  position-position-2708:
    title: Слайдер
    attributes:
      key: slider
    block:
      variations: 'nopaddingall nomarginall'
  custom-2879:
    title: 'Custom HTML'
  custom-7663:
    title: 'Custom HTML'
  custom-5650:
    title: 'Custom HTML'
  sample-2:
    title: 'Getting Started'
    attributes:
      description: "<h1 class=\"center\">Getting Started</h1>\n<div class=\"device-promo\"><div class=\"macbook\"><div class=\"macbook-color\"></div></div><div class=\"ipad\"><div class=\"ipad-color\"></div></div><div class=\"iphone\"><div class=\"iphone-color\"></div></div></div><p>Welcome to Gantry 5 featuring <strong>Hydrogen</strong>, the first theme built on the Gantry 5 framework. If you want to get started, the best way is to navigate to the Gantry Administrator via your platform's Administration panel.</p>\n\n<p>Once you are in the Gantry 5 Administrator, you will be able to edit virtually every aspect of your site from its <strong>Layout</strong> to its <strong>Style</strong>. You can even refine how the menus appear using Gantry 5’s new <strong>Menu Editor</strong>.</p>\n\n<p>You can set different style preferences for different pages, and have them assigned accordingly using the <strong>Assignments</strong> administrative panel.</p>\n\n<div class=\"info-box\"><div class=\"fa fa-graduation-cap float-left\"></div><p>Look for more information on Gantry 5 in our documentation, and stay tuned to the RocketTheme Blog for more information on new features and development updates as development continues.</p>\n\n<p><a href=\"http://docs.gantry.org\" class=\"button\">Learn More</a></p></div>\n\n<h1 class=\"center\">How to Contribute</h1>\n\n<div class=\"g-grid\">\n<div class=\"g-block size-37\"><p>Thank you for using Gantry 5 and the Hydrogen theme. We welcome you to contribute to the project by submitting bug reports through <strong>GitHub</strong>, and/or submit your own code changes to the <strong>Gantry 5 project</strong> for consideration.</p>\n<p><a href=\"https://github.com/gantry/gantry5\" class=\"button\">Gantry 5 on GitHub</a></p>\n</div>\n<div class=\"g-block size-26 middle\"><div class=\"fa fa-github-square\"></div></div>\n\n<div class=\"g-block size-37\"><p>If you would like to assist in creating documentation for Gantry 5, you can do so through the <strong>Gantry 5 Documentation</strong> project on <strong>GitHub</strong>.</p>\n<p><a href=\"https://github.com/gantry/docs\" class=\"button\">Gantry Docs on GitHub</a></p>\n</div>\n</div>\n\n<p>Once again, thank you for participating. We hope you enjoy testing Gantry 5 every bit as much as we have enjoyed creating it.</p>"
  position-footer:
    attributes:
      key: footer
  mobile-menu-6240:
    title: 'Mobile Menu'
